compilation:
  cloud_properties:
    cpu: 1
    disk: 1096
    ram: 1096
  network: default-network
  reuse_compilation_vms: true
  workers: 1
director_uuid: 02bc17b4-68f8-4124-afd0-3bf6acd07473
jobs:
- instances: 1
  name: postgres
  networks:
  - name: default-network
    static_ips:
    - 10.244.0.2
  persistent_disk: 2024
  release: bosh_intro
  resource_pool: default-pool
  template: postgres
- instances: 1
  name: tomcat
  networks:
  - name: default-network
    static_ips:
    - 10.244.0.6
  persistent_disk: 2024
  release: bosh_intro
  resource_pool: default-pool
  template: tomcat
name: bosh_intro_deployment
networks:
- name: default-network
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.0.0/30
    reserved:
    - 10.244.0.1
    static:
    - 10.244.0.2
  - cloud_properties:
      name: random
    range: 10.244.0.4/30
    reserved:
    - 10.244.0.5
    static:
    - 10.244.0.6
  - cloud_properties:
      name: random
    range: 10.244.0.8/30
releases:
- name: bosh_intro
  version: latest
resource_pools:
- cloud_properties:
    cpu: 1
    disk: 1024
    ram: 1024
  name: default-pool
  network: default-network
  size: 2
  stemcell:
    name: bosh-warden-boshlite-ubuntu-lucid-go_agent
    version: 60
update:
  canaries: 1
  canary_watch_time: 30000-300000
  max_errors: 2
  max_in_flight: 1
  update_watch_time: 30000-300000

